version: "3.9"
services:
  email-queue:
    image: rabbitmq
    container_name: notize-mail-queue
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
